spring:
  application:
    name: inscription-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inscription-service
    username: babaGM
    password: GalsenMedic123!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show_sql: true
server:
  port: 8089
springdoc:
  api-docs:
    path: /api-docs
services:
  gestion-scolarite:
    url: http://localhost:8088
  gestion-etudiant:
    url: http://localhost:8081